# Generated by Django 3.2.19 on 2023-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
