# Generated by Django 3.2.19 on 2023-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='chosen',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
